Global class ResponseBuilder{
 public class responseWrapper{
        @AuraEnabled
        public String date_range;
        @AuraEnabled
        public String current_date;
        @AuraEnabled
        public String description;
        @AuraEnabled
        public String compatibility;
        @AuraEnabled
        public String mood;
        @AuraEnabled
        public String color;
        @AuraEnabled
        public String lucky_number;
        @AuraEnabled
        public String lucky_time;
    }
}